name: Trigger Target Workflow

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger target repository workflow
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          curl -X POST \
            -H "Authorization: token $PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/P-Harini/Mason-TargetRepo-Shoemall/dispatches \
            -d '{"event_type":"trigger_workflow"}'
